In [1]:
from sklearn.neighbors import NearestNeighbors
>>> import numpy as np

In [2]:
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])

In [3]:
nbrs = NearestNeighbors(n_neighbors=2, algorithm='ball_tree').fit(X)

In [4]:
distances, indices = nbrs.kneighbors(X)

In [5]:
indices

array([[0, 1],
       [1, 0],
       [2, 1],
       [3, 4],
       [4, 3],
       [5, 4]], dtype=int64)

In [6]:
distances

array([[0.        , 1.        ],
       [0.        , 1.        ],
       [0.        , 1.41421356],
       [0.        , 1.        ],
       [0.        , 1.        ],
       [0.        , 1.41421356]])

In [7]:
nbrs.kneighbors_graph(X).toarray()

array([[1., 1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 1., 1.]])

In [16]:
import numpy as np
from sklearn.neighbors import KDTree


In [9]:
dist = DistanceMetric.get_metric('euclidean')

In [58]:
X = np.asarray([[1, 1], [2, 2] , [3,3]])
Y = np.asarray([1,2,3,4,5])
Z = np.asarray([1,2,3,4,5])
A = np.asarray([Y,Z])
A = np.transpose(A)
A

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5]])

In [59]:
tree = KDTree(A) 

In [60]:
dist, ind = tree.query([[3,3]] , k=3)   

In [61]:
dist

array([[0.        , 1.41421356, 1.41421356]])

In [67]:
ind[0][2]

1